### ISSUE TITLE
Device service runs on docker

### ISSUE THREAD

**Issue by hoihkj** [edgexfoundry/device-random#23]
Hi, I compile and build the device-random project and could get values with http://localhost:48080 command. I want to know how could I run this service on docker as example in docker-compose.yml from edgex foundry compose file. Thanks.

https://docs.edgexfoundry.org/Ch-QuickStart.html

http://localhost:48080/api/v1/event/device/Random-Integer-Generator01/10

**Comment by cloudxxx8** [comment]
@hoihkj It is not a real issue, but a question.
Please put your question on slack, and the community members could answer or discuss with you on that.  Thanks
https://edgexfoundry.slack.com/messages/CE44YG81E/details/

**Comment by hoihkj** [comment]
> Hi, I compile and build the device-random project and could get values with http://localhost:48080 command. I want to know how could I run this service on docker as example in docker-compose.yml from edgex foundry compose file. Thanks.
> 
> https://docs.edgexfoundry.org/Ch-QuickStart.html
> 
> http://localhost:48080/api/v1/event/device/Random-Integer-Generator01/10

I am sorry to post here, but I do not have a account on slack, could you please send a invitation to me, thanks.

**Comment by jpwhitemn** [comment]
Hi Hoihkj -No problem posting your question here - thank you for the interest in the project.
If you pull the Delhi 0.7.1 docker compose file (from here:  https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-delhi-0.7.1.yml) you will see that the device-random is already listed as one of the optional device services to pull and include in your EdgeX execution.   The device-random service is listed right below the device-virtual and is commented out.  You simply need to uncomment these lines (starting at line 269):
#  device-random:
#    image: edgexfoundry/docker-device-random-go:0.7.1
#    ports:
#      - "49988:49988"
#    container_name: edgex-device-random
#    hostname: edgex-device-random
#    networks:
#      - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
#    depends_on:
#      - data
#      - command
The Docker image is already in Docker Hub if yo want to create your own compose file.https://hub.docker.com/r/edgexfoundry/docker-device-random-go

Jim



    On Tuesday, December 25, 2018, 1:42:49 AM CST, hoihkj <notifications@github.com> wrote:  
 
 

Hi, I compile and build the device-random project and could get values with http://localhost:48080 command. I want to know how could I run this service on docker as example in docker-compose.yml from edgex foundry compose file. Thanks.

https://docs.edgexfoundry.org/Ch-QuickStart.html

http://localhost:48080/api/v1/event/device/Random-Integer-Generator01/10


I am sorry to post here, but I do not have a account on slack, could you please send a invitation to me, thanks.
