### ISSUE TITLE
Update to use Device.Protocols and remove Schedule/ScheduleEvent usage

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-random#35]
device-random as of the latest code in master no longer works when run against the latest edgex-go code due to the replacement of `Device.Addressable` with `Device.Protocols`.  I discovered this by installing the edgexfoundry snap from the edge channel (`sudo snap install edgexfoundry --edge`) and noticing that device-random fails to start if enabled (`sudo snap config edgexfoundry device-random=on`).

The same `Device` **configuration.toml** changes that were made to device-sdk-go in commit [fc71221](https://github.com/edgexfoundry/device-sdk-go/commit/fc712212962e7a52da8ff0b7d6a8734cc5af8bdd) need to be applied. 

Likewise the Schedule* **configuration.toml** changes (see device-sdk-go commit [2db9552](https://github.com/edgexfoundry/device-sdk-go/commit/2db9552350484545cc2f0750a9a33b6f572fc05c) also need to be applied.

**Comment by cloudxxx8** [comment]
@FelixTing is working on this issue and will open PR after https://github.com/edgexfoundry/device-sdk-go/issues/197 closed
