### ISSUE TITLE
Device Random code improvement

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/device-random#65]
The values checked for are constants, defined once.
Each time we request a value, we should not have to test for sane range. It could be performed in some kind of init function.

https://github.com/edgexfoundry/device-random/blob/8a39ed9383f5e332113c037cbc7802181337a035/driver/randomdevice.go#L35

**Comment by cloudxxx8** [comment]
We check it every time because we allow the put command to modify the min and max value of the random device at runtime.

**Comment by mkbhanda** [comment]
Thank you Cloud for explaining!! Would you please add this explanation as a comment in the code.
Sincerely
Malini


Sent from VMware Boxer

On June 13, 2019 at 10:05:29 PM PDT, Cloud Tsai <notifications@github.com> wrote:

We check it every time because we allow the put command to modify the min and max value of the random device at runtime.
